# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version: 2

palette:
  catppuccin_latte_rosewater: "#dc8a78"
  catppuccin_latte_flamingo: "#dd7878"
  catppuccin_latte_pink: "#ea76cb"
  catppuccin_latte_mauve: "#8839ef"
  catppuccin_latte_red: "#d20f39"
  catppuccin_latte_maroon: "#e64553"
  catppuccin_latte_peach: "#fe640b"
  catppuccin_latte_yellow: "#df8e1d"
  catppuccin_latte_green: "#40a02b"
  catppuccin_latte_teal: "#179299"
  catppuccin_latte_sky: "#04a5e5"
  catppuccin_latte_sapphire: "#209fb5"
  catppuccin_latte_blue: "#1e66f5"
  catppuccin_latte_lavender: "#7287fd"
  catppuccin_latte_text: "#4c4f69"
  catppuccin_latte_subtext1: "#5c5f77"
  catppuccin_latte_subtext0: "#6c6f85"
  catppuccin_latte_overlay2: "#7c7f93"
  catppuccin_latte_overlay1: "#8c8fa1"
  catppuccin_latte_overlay0: "#9ca0b0"
  catppuccin_latte_surface2: "#acb0be"
  catppuccin_latte_surface1: "#bcc0cc"
  catppuccin_latte_surface0: "#ccd0da"
  catppuccin_latte_base: "#eff1f5"
  catppuccin_latte_mantle: "#e6e9ef"
  catppuccin_latte_crust: "#dce0e8"

blocks:
  - type: prompt
    alignment: left
    segments:
      - type: os
        style: plain
        foreground: "p:catppuccin_latte_teal"
        template: "{{ if .WSL }}WSL at {{ end }}{{.Icon}}"
        properties:
          windows: ğŸªŸ
          macos: ğŸ
          linux: ğŸ§
          alma: ğŸ§
          almalinux: ğŸ§
          almalinux9: ğŸ§
          alpine:  ğŸ§
          android: ğŸ§
          aosc: ğŸ§
          arch: ğŸ§
          centos: ğŸ§
          coreos: ğŸ§
          debian: ğŸ§
          deepin: ğŸ§
          devuan: ğŸ§
          elementary: ğŸ§
          endeavouros: ğŸ§
          fedora: ğŸ§
          gentoo: ğŸ§
          mageia: ğŸ§
          manjaro: ğŸ§
          mint: ğŸ§
          nixos: ğŸ§
          opensuse: ğŸ§
          opensuse-tumbleweed: ğŸ§
          raspbian: ğŸ§
          redhat: ğŸ§
          rocky: ğŸ§
          sabayon: ğŸ§
          slackware: ğŸ§
          ubuntu: ğŸ§

      - type: path
        style: plain
        foreground: "p:catppuccin_latte_sky"
        template: " ó°‰‹ {{ .Path }}"
        properties:
          style: powerlevel

      - type: git
        style: plain
        foreground: "p:catppuccin_latte_green"
        template: ' {{ .UpstreamIcon }} {{ .HEAD }}{{
          if and (.BranchStatus) (ne .BranchStatus "â‰¡")}} <p:catppuccin_latte_yellow>{{ .BranchStatus }}</>{{ end }}{{
          if and (.BranchStatus) (eq .BranchStatus "â‰¡")}} <p:catppuccin_latte_green>{{ .BranchStatus }}</>{{ end }}{{
          if .Working.Changed }} <p:catppuccin_latte_maroon>î©³</>{{ end }}{{
          if .Staging.Changed }} <p:catppuccin_latte_yellow>ï† </>{{ end }}{{
          if gt .StashCount 0 }} <p:catppuccin_latte_red>ï” {{ .StashCount }}</>{{ end }}'
        properties:
          fetch_status: true
          fetch_upstream_icon: true

          commit_icon: "ï— "
          tag_icon: "ï’ "
          rebase_icon: "îœ¨ "
          cherry_pick_icon: "îŠ› "
          revert_icon: "ïƒ¢ "
          merge_icon: "îœ§ "
          no_commits_icon: "? "
          branch_icon: "î‚ "
          branch_identical_icon: "â‰¡"
          branch_ahead_icon: "â†‘"
          branch_behind_icon: "â†“"
          branch_gone_icon: "â‰¢"
          branch_max_length: 25
          truncate_symbol: "â€¦"

          upstream_icons:
            "iis-git.ee.ethz.ch": "ï‡“ iis"
            "git.ee.ethz.ch": "ï‡“ eth"

      - type: text
        style: plain
        foreground: "p:catppuccin_latte_green"
        template: " â¯ "

  - type: rprompt
    segments:
      - type: executiontime
        style: plain
        foreground: "p:catppuccin_latte_sky"
        template: "ó°…’ {{ .FormattedMs }} "
        properties:
          threshold: 150
          style: austin
          always_enabled: false

      - type: status
        style: plain
        foreground: "p:catppuccin_latte_red"
        template: "{{ if .Error }}!{{ .String }} {{ end }}"
        properties:
          always_enabled: true

      - type: session
        style: plain
        foreground: "p:catppuccin_latte_flamingo"
        template: "{{ if .SSHSession }} î®© {{ .UserName }}{{ end }}"

      - type: rust
        style: plain
        foreground: "p:catppuccin_latte_flamingo"
        template: "î¨ {{ .Full }} "

      - type: python
        style: plain
        foreground: "p:catppuccin_latte_flamingo"
        template: "îˆµ  {{ .Venv }} ({{ .Full }}) "

      - type: docker
        style: plain
        foreground: "p:catppuccin_latte_flamingo"
        template: "ïŒˆ  {{ .Context }} "

      - type: time
        style: plain
        foreground: "p:catppuccin_latte_sky"
        template: "ï€— {{ .CurrentDate | date .Format }} "
        properties:
          time_format: "15:04:05"
